In [1]:
%matplotlib inline

import matplotlib.pyplot as plt
from pandas import DataFrame
import pandas as pd
import numpy as np
from class3 import Anisotropy

In [2]:
df = pd.read_csv('data/anisotropy1.csv')
#.read_data_file('C:/Users/BUYPC COMPUTERS/Desktop/MY PROJECT/4a_binomial_package/anisotropy.csv', True)

In [3]:
df.head(3)

   Depth  Vint_cks(m/s)  Vint_seismic(m/s)
0   1350        2813.00            2815.27
1   1506        2871.95            2955.16
2   1620        2901.91            3048.92

In [4]:
test = Anisotropy(df)

In [5]:
print(type(test))

<class 'class3.Anisotropy'>

In [6]:
x = test.thomsen_delta(1, 2)

In [7]:
x.head()

   Depth  Vint_cks(m/s)  Vint_seismic(m/s)  Thomsen_delta
0   1350        2813.00            2815.27       0.000807
1   1506        2871.95            2955.16       0.028973
2   1620        2901.91            3048.92       0.050660
3   1720        2921.40            3110.14       0.064606
4   1778        2998.67            3290.80       0.097420
5   1856        3060.11            3375.43       0.103042
6   1920        3220.24            3497.41       0.086071
7   2076        3388.80            3574.06       0.054668
8   2154        3544.37            3623.78       0.022405

In [9]:
y = test.anisotropy_correction(2)

In [10]:
y.head()

,Depth,Vint_cks(m/s),Vint_seismic(m/s),Thomsen_delta,Anisotropy_correction
0,1350,2813.00,2815.27,0.000807,2812.998168
1,1506,2871.95,2955.16,0.028973,2869.539128
2,1620,2901.91,3048.92,0.050660,2894.462512
3,1720,2921.40,3110.14,0.064606,2909.206262
4,1778,2998.67,3290.80,0.097420,2970.210737
5,1856,3060.11,3375.43,0.103042,3027.618782
6,1920,3220.24,3497.41,0.086071,3196.383639
7,2076,3388.80,3574.06,0.054668,3378.672147
8,2154,3544.37,3623.78,0.022405,3542.590855

In [12]:
df.to_csv('data/anisotropy2.csv', index=False)

In [ ]:
z = test.plot_data()

In [ ]:
# Unit tests to check your solution

import unittest

class TestGaussianClass(unittest.TestCase):
    def setUp(self):
        self.gaussian = Gaussian(3080.05, 252.2692)

    def test_initialization(self): 
        self.assertEqual(self.gaussian.mean, 3080.05, 'incorrect mean')
        self.assertEqual(self.gaussian.stdev, 252.2692, 'incorrect standard deviation')

    def test_pdf(self):
        self.assertEqual(round(self.gaussian.pdf(25), 5), 0.0,\
         'pdf function does not give expected result') 

    def test_meancalculation(self):
        self.gaussian.read_data_file('anisotropy.csv', True)
        self.assertEqual(self.gaussian.calculate_calculate_thomsen_delta(),\
         sum(self.gaussian.data) / float(len(self.gaussian.data)), 'calculated mean not as expected')

    def test_stdevcalculation(self):
        self.gaussian.read_data_file('anisotropy.csv', True)
        self.assertEqual(round(self.gaussian.stdev, 2), 252.27, 'sample standard deviation incorrect')
        self.gaussian.read_data_file('anisotropy.csv', False)
        self.assertEqual(round(self.gaussian.stdev, 2), 237.84, 'population standard deviation incorrect')
                
tests = TestGaussianClass()

tests_loaded = unittest.TestLoader().loadTestsFromModule(tests)

unittest.TextTestRunner().run(tests_loaded)